apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-tls
  namespace: example-com
spec:
  secretName: example-com-tls
  duration: 2160h
  renewBefore: 48h
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: example.com
  dnsNames:
    - example.com
    - www.example.com
